
package Main;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

public class Laporan_Pelanggan extends javax.swing.JPanel {

    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = Koneksi.Koneksi();
    
    public void judul(){
        Object[] judul = {"Kode Pelanggan", "Nama Pelanggan", "No Telepon", "Alamat", "Tanggal Sewa"};
        
        tabModel = new DefaultTableModel(null, judul){
            @Override
            public boolean isCellEditable(int row, int column) {    //CELL TABLE TIDAK BISA DI EDIT
                return false; // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }
            
        };
        tb_dataPelanggan.setModel(tabModel);
    }
    
        public void tampilData() {      //Tidak Menggunakan txt_pencarian
        tabModel.setRowCount(0); 

        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_pelanggan");

            while (rs.next()) {
                Object[] data = {
                    rs.getString("kode_pelanggan"),
                    rs.getString("nama_pelanggan"),
                    rs.getString("no_tlpPelanggan"),
                    rs.getString("alamat_pelanggan"),
                    rs.getString("tanggal_sewa")
                };
                tabModel.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    
//    public void tampilData(String where){
//        tabModel.setRowCount(0);
//    
//        String cari = txt_pencarian.getText();  //Menggunakan txt_pencarian
//        try {
//            st = cn.createStatement();
//            rs = st.executeQuery("SELECT * FROM tb_pelanggan WHERE "
//                    + "kode_pelanggan LIKE '%" + cari + "%' OR "
//                    + "nama_pelanggan LIKE '%" + cari + "%' OR "
//                    + "no_tlpPelanggan LIKE '%" + cari + "%' OR "
//                    + "alamat_pelanggan LIKE '%" + cari + "%' OR "
//                    + "tanggal_sewa LIKE '%" + cari + "%'");
//
//            while (rs.next()) {
//                Object[] data = {
//                    rs.getString("kode_pelanggan"),
//                    rs.getString("nama_pelanggan"),
//                    rs.getString("no_tlpPelanggan"),
//                    rs.getString("alamat_pelanggan"),
//                    rs.getString("tanggal_sewa")
//                };
//                tabModel.addRow(data);
//            }
//        } catch (SQLException e) {
//                e.printStackTrace();
//        }
//    }
    
    /**
     * Creates new form 
     */
    public Laporan_Pelanggan() {
        initComponents();
        
        judul();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Laporan = new javax.swing.JPanel();
        label_Laporan = new javax.swing.JLabel();
        scroll_table = new javax.swing.JScrollPane();
        tb_dataPelanggan = new Custom.TableCustom();
        lb_pencarian = new javax.swing.JLabel();
        txt_pencarian = new javax.swing.JTextField();

        panel_Laporan.setBackground(new java.awt.Color(255, 255, 255));

        label_Laporan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_Laporan.setText("Laporan Pelanggan");

        tb_dataPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_dataPelanggan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tb_dataPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dataPelangganMouseClicked(evt);
            }
        });
        scroll_table.setViewportView(tb_dataPelanggan);

        lb_pencarian.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_pencarian.setText("PENCARIAN");

        txt_pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pencarianKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_LaporanLayout = new javax.swing.GroupLayout(panel_Laporan);
        panel_Laporan.setLayout(panel_LaporanLayout);
        panel_LaporanLayout.setHorizontalGroup(
            panel_LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LaporanLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(label_Laporan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_LaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_table, javax.swing.GroupLayout.DEFAULT_SIZE, 1258, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LaporanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_LaporanLayout.setVerticalGroup(
            panel_LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Laporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(panel_LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_LaporanLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lb_pencarian))
                    .addComponent(txt_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_table, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_dataPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataPelangganMouseClicked
        //klikTabel("");
    }//GEN-LAST:event_tb_dataPelangganMouseClicked

    private void txt_pencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pencarianKeyReleased
        //tampilData("");
    }//GEN-LAST:event_txt_pencarianKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_Laporan;
    private javax.swing.JLabel lb_pencarian;
    private javax.swing.JPanel panel_Laporan;
    private javax.swing.JScrollPane scroll_table;
    private Custom.TableCustom tb_dataPelanggan;
    private javax.swing.JTextField txt_pencarian;
    // End of variables declaration//GEN-END:variables
}
