/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import javax.swing.JOptionPane;

/**
 *
 * @author Ramadhani
 */
public class Form_LapStokSewa extends javax.swing.JFrame {

    /**
     * Creates new form Form_LapStokSewa
     */
    public Form_LapStokSewa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_dataBarang = new javax.swing.JPanel();
        lb_formDataSW = new javax.swing.JLabel();
        lb_namaBarang = new javax.swing.JLabel();
        lb_kodeBarang = new javax.swing.JLabel();
        lb_stokSewa = new javax.swing.JLabel();
        lb_hargaSatuan = new javax.swing.JLabel();
        namaBarang = new javax.swing.JComboBox<>();
        kodeBarang = new javax.swing.JTextField();
        stokSewa = new javax.swing.JTextField();
        hargaSatuan = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_dataBarang.setBackground(new java.awt.Color(255, 255, 255));

        lb_formDataSW.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lb_formDataSW.setText("FORM LAPORAN STOK SEWA");

        lb_namaBarang.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_namaBarang.setText("Nama Barang");

        lb_kodeBarang.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_kodeBarang.setText("Kode Barang");

        lb_stokSewa.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_stokSewa.setText("Stok Sewa");

        lb_hargaSatuan.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_hargaSatuan.setText("Harga Satuan");

        namaBarang.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        namaBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang", "AC Split 1 PK", "AC Split 2 PK", "AC Standing 3 PK", "AC Standing 5 PK", "AC Portable 1 PK", "AC Portable 1,5 PK", "Misty Cool" }));

        kodeBarang.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        stokSewa.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        hargaSatuan.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_dataBarangLayout = new javax.swing.GroupLayout(panel_dataBarang);
        panel_dataBarang.setLayout(panel_dataBarangLayout);
        panel_dataBarangLayout.setHorizontalGroup(
            panel_dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dataBarangLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(panel_dataBarangLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel_dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_stokSewa)
                    .addComponent(lb_hargaSatuan)
                    .addComponent(lb_kodeBarang)
                    .addComponent(lb_namaBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaBarang, 0, 300, Short.MAX_VALUE)
                    .addComponent(kodeBarang)
                    .addComponent(stokSewa)
                    .addComponent(hargaSatuan))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dataBarangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_formDataSW)
                .addGap(94, 94, 94))
        );
        panel_dataBarangLayout.setVerticalGroup(
            panel_dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dataBarangLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lb_formDataSW)
                .addGap(38, 38, 38)
                .addGroup(panel_dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_namaBarang))
                .addGap(18, 18, 18)
                .addGroup(panel_dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_kodeBarang))
                .addGap(18, 18, 18)
                .addGroup(panel_dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stokSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_stokSewa))
                .addGap(18, 18, 18)
                .addGroup(panel_dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_hargaSatuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(panel_dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_batal))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_dataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_dataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        int pilih = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin SIMPAN?",
            "SIMPAN", JOptionPane.OK_CANCEL_OPTION);
        if(pilih == JOptionPane.OK_OPTION){
        }
        dispose();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        int pilih = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin Keluar?",
            "OK", JOptionPane.OK_CANCEL_OPTION);
        if(pilih == JOptionPane.OK_OPTION){
            //            System.exit(0);
            dispose();
        } else {
            JOptionPane.getRootFrame();
        }
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_LapStokSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_LapStokSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_LapStokSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_LapStokSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_LapStokSewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JTextField hargaSatuan;
    private javax.swing.JTextField kodeBarang;
    private javax.swing.JLabel lb_formDataSW;
    private javax.swing.JLabel lb_hargaSatuan;
    private javax.swing.JLabel lb_kodeBarang;
    private javax.swing.JLabel lb_namaBarang;
    private javax.swing.JLabel lb_stokSewa;
    private javax.swing.JComboBox<String> namaBarang;
    private javax.swing.JPanel panel_dataBarang;
    private javax.swing.JTextField stokSewa;
    // End of variables declaration//GEN-END:variables
}
