package Main;

//import com.sun.jdi.connect.spi.Connection;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Form_Login extends javax.swing.JFrame {
    int xx, xy;
    /**
     * Creates new form Form_Login
     */
    public Form_Login() {
        initComponents();
        setLocationRelativeTo(this);
        
        txtUsername.addKeyListener(new KeyAdapter() {
        @Override
            public void keyTyped(KeyEvent e) {
                // Mendapatkan karakter yang diketik
                char c = e.getKeyChar();
                // Jika karakter adalah huruf kecil, ubah menjadi huruf besar
                if (Character.isLowerCase(c)) {
                    e.setKeyChar(Character.toUpperCase(c));
                }
            }
        });
    }
    
    void bersih(){
        txtUsername.setText("Username");
        txtPassword.setText("Password");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_all = new javax.swing.JPanel();
        panel_navbar = new javax.swing.JPanel();
        lb_logoNavbar = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        lb_logo = new javax.swing.JLabel();
        lb_login = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btn_login = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        panel_all.setBackground(new java.awt.Color(255, 255, 255));
        panel_all.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_all.setForeground(new java.awt.Color(255, 255, 255));
        panel_all.setPreferredSize(new java.awt.Dimension(750, 420));

        panel_navbar.setBackground(new java.awt.Color(204, 0, 0));
        panel_navbar.setForeground(new java.awt.Color(255, 255, 255));
        panel_navbar.setPreferredSize(new java.awt.Dimension(749, 116));
        panel_navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_logoNavbar.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        lb_logoNavbar.setText("PT . INDOJAYA MULTI TEKNIK");
        panel_navbar.add(lb_logoNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 42, -1, -1));

        btn_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconExit_30px.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        panel_navbar.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoIndojaya_80px.jpg"))); // NOI18N

        lb_login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_login.setText("LOGIN");

        txtUsername.setBackground(java.awt.SystemColor.control);
        txtUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setText("USERNAME");
        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });

        txtPassword.setBackground(java.awt.SystemColor.control);
        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setText("Password");
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(204, 204, 204));
        btn_login.setForeground(new java.awt.Color(0, 0, 0));
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_allLayout = new javax.swing.GroupLayout(panel_all);
        panel_all.setLayout(panel_allLayout);
        panel_allLayout.setHorizontalGroup(
            panel_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_navbar, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
            .addGroup(panel_allLayout.createSequentialGroup()
                .addGroup(panel_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_allLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(panel_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_allLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lb_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_allLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_allLayout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(lb_login)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_allLayout.setVerticalGroup(
            panel_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_allLayout.createSequentialGroup()
                .addComponent(panel_navbar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_login)
                .addGap(18, 18, 18)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_all, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_all, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        String username = txtUsername.getText();
        if(username.equals("USERNAME")){
            txtUsername.setText("");
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        String username = txtUsername.getText();
        if(username.equals("")||username.equals("USERNAME")){
            txtUsername.setText("USERNAME");
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        String pass = txtPassword.getText();
        if(pass.equals("Password")){
            txtPassword.setText("");
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        String pass = txtPassword.getText();
        if(pass.equals("")||pass.equals("Password")){
            txtPassword.setText("Password");
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // System.out.println("Sign up btn clicked");
        String Username, Password, query, namaLengkap = null, passwordDb = null;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/db_indojaya";
        SUser = "root";
        SPass = "";
        int notFound = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            if("".equals(txtUsername.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Username Diperlukan", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(txtPassword.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Password Diperlukan", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else {
            Username = txtUsername.getText();
            Password = txtPassword.getText();
            
            query = "SELECT * FROM tb_akun WHERE username= '"+Username+"'";
       
            ResultSet rs = st.executeQuery(query);
            while(rs.next()){
                passwordDb = rs.getString("password");
                namaLengkap = rs.getString("nama_lengkap");
                notFound = 1;
            }
            if(notFound == 1 && Password.equals(passwordDb)){
                Menu_Utama HomeFrame = new Menu_Utama();
                HomeFrame.setUser(Username+" - "+namaLengkap);
                HomeFrame.setVisible(true);
                this.dispose();
            }else{
               JOptionPane.showMessageDialog(new JFrame(), "Username atau Password Salah", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
            txtPassword.setText("");
            
            }
        }catch(Exception e){
           System.out.println("Error!" + e.getMessage()); 
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_close;
    private rojerusan.RSMaterialButtonRectangle btn_login;
    private javax.swing.JLabel lb_login;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_logoNavbar;
    private javax.swing.JPanel panel_all;
    private javax.swing.JPanel panel_navbar;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
