/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

/**
 *
 * @author Ramadhani
 */
public class Laporan_Barang extends javax.swing.JPanel {

    /**
     * Creates new form Laporan
     */
    public Laporan_Barang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Laporan = new javax.swing.JPanel();
        label_Laporan = new javax.swing.JLabel();
        scroll_table = new javax.swing.JScrollPane();
        tb_transPnw = new Custom.TableCustom();
        lb_pencarian = new javax.swing.JLabel();
        txt_pencarian = new javax.swing.JTextField();

        panel_Laporan.setBackground(new java.awt.Color(255, 255, 255));

        label_Laporan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_Laporan.setText("Laporan Barang");

        tb_transPnw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_transPnw.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tb_transPnw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_transPnwMouseClicked(evt);
            }
        });
        scroll_table.setViewportView(tb_transPnw);

        lb_pencarian.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_pencarian.setText("PENCARIAN");

        txt_pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pencarianKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_LaporanLayout = new javax.swing.GroupLayout(panel_Laporan);
        panel_Laporan.setLayout(panel_LaporanLayout);
        panel_LaporanLayout.setHorizontalGroup(
            panel_LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LaporanLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(label_Laporan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_LaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_table, javax.swing.GroupLayout.DEFAULT_SIZE, 1258, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LaporanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_LaporanLayout.setVerticalGroup(
            panel_LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Laporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(panel_LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_LaporanLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lb_pencarian))
                    .addComponent(txt_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_table, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_transPnwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_transPnwMouseClicked
        //klikTabel("");
    }//GEN-LAST:event_tb_transPnwMouseClicked

    private void txt_pencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pencarianKeyReleased
        //tampilData("");
    }//GEN-LAST:event_txt_pencarianKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_Laporan;
    private javax.swing.JLabel lb_pencarian;
    private javax.swing.JPanel panel_Laporan;
    private javax.swing.JScrollPane scroll_table;
    private Custom.TableCustom tb_transPnw;
    private javax.swing.JTextField txt_pencarian;
    // End of variables declaration//GEN-END:variables
}
