/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

/**
 *
 * @author Ramadhani
 */
public class Transaksi_Sewa extends javax.swing.JPanel {

    /**
     * Creates new form Transaksi_Penyewaan
     */
    public Transaksi_Sewa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_TransSewa = new javax.swing.JPanel();
        lb_TransSewa = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        lb_pencarian = new javax.swing.JLabel();
        txt_pencarian = new javax.swing.JTextField();
        scroll_table = new javax.swing.JScrollPane();
        tb_transPnw = new Custom.TableCustom();
        lb_formTransSewa = new javax.swing.JLabel();
        lb_kodePlg = new javax.swing.JLabel();
        txt_kodePlg = new javax.swing.JTextField();
        lb_namaPlg = new javax.swing.JLabel();
        txt_namaPlg = new javax.swing.JTextField();
        lb_noTlpPlg = new javax.swing.JLabel();
        txt_noTlpPlg = new javax.swing.JTextField();
        lb_alamatPlg = new javax.swing.JLabel();
        scroll_alamat = new javax.swing.JScrollPane();
        txt_alamatPlg = new javax.swing.JTextArea();
        lb_tglSewa = new javax.swing.JLabel();
        date_tglSewa = new com.toedter.calendar.JDateChooser();
        lb_noTransSewa = new javax.swing.JLabel();
        txt_noTransSewa = new javax.swing.JTextField();
        lb_namaBrgSewa = new javax.swing.JLabel();
        cb_namaBrgSewa = new javax.swing.JComboBox<>();
        lb_jmlBrgSewa = new javax.swing.JLabel();
        txt_jmlBrgSewa = new javax.swing.JTextField();
        lb_hargaSatuan = new javax.swing.JLabel();
        txt_hargaSatuan = new javax.swing.JTextField();
        lb_totalHarga = new javax.swing.JLabel();
        txt_totalHarga = new javax.swing.JTextField();

        panel_TransSewa.setBackground(new java.awt.Color(255, 255, 255));
        panel_TransSewa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_TransSewa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb_TransSewa.setText("Transaksi Sewa");
        panel_TransSewa.add(lb_TransSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        btn_simpan.setBackground(new java.awt.Color(102, 255, 102));
        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconAdd_25px.png"))); // NOI18N
        btn_simpan.setText("SIMPAN");
        btn_simpan.setBorderPainted(false);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        panel_TransSewa.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 112, -1));

        btn_edit.setBackground(new java.awt.Color(51, 204, 255));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconUpdate_25px.png"))); // NOI18N
        btn_edit.setText("EDIT");
        btn_edit.setBorderPainted(false);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        panel_TransSewa.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 72, -1, -1));

        btn_hapus.setBackground(new java.awt.Color(255, 51, 0));
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconDelete_25px.png"))); // NOI18N
        btn_hapus.setText("HAPUS");
        btn_hapus.setBorderPainted(false);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        panel_TransSewa.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 72, -1, -1));

        btn_reset.setBackground(java.awt.Color.yellow);
        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconCancel_25px.png"))); // NOI18N
        btn_reset.setText("RESET");
        btn_reset.setBorderPainted(false);
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        panel_TransSewa.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 72, -1, -1));

        lb_pencarian.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_pencarian.setText("PENCARIAN");
        panel_TransSewa.add(lb_pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(953, 79, -1, -1));

        txt_pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pencarianKeyReleased(evt);
            }
        });
        panel_TransSewa.add(txt_pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1064, 74, 200, 30));

        tb_transPnw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_transPnw.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tb_transPnw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_transPnwMouseClicked(evt);
            }
        });
        scroll_table.setViewportView(tb_transPnw);

        panel_TransSewa.add(scroll_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 110, 745, 564));

        lb_formTransSewa.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lb_formTransSewa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_formTransSewa.setText("Form Transaksi Sewa");
        panel_TransSewa.add(lb_formTransSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 144, 460, -1));

        lb_kodePlg.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_kodePlg.setText("Kode Pelanggan");
        panel_TransSewa.add(lb_kodePlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 196, -1, -1));

        txt_kodePlg.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_kodePlg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_kodePlgKeyTyped(evt);
            }
        });
        panel_TransSewa.add(txt_kodePlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 193, 250, -1));

        lb_namaPlg.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_namaPlg.setText("Nama Pelanggan");
        panel_TransSewa.add(lb_namaPlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        txt_namaPlg.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        panel_TransSewa.add(txt_namaPlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 237, 250, -1));

        lb_noTlpPlg.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_noTlpPlg.setText("No Telepon");
        panel_TransSewa.add(lb_noTlpPlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 284, -1, -1));

        txt_noTlpPlg.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        panel_TransSewa.add(txt_noTlpPlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 281, 250, -1));

        lb_alamatPlg.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_alamatPlg.setText("Alamat");
        panel_TransSewa.add(lb_alamatPlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 325, -1, -1));

        txt_alamatPlg.setColumns(20);
        txt_alamatPlg.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_alamatPlg.setRows(5);
        scroll_alamat.setViewportView(txt_alamatPlg);

        panel_TransSewa.add(scroll_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 325, 250, 70));

        lb_tglSewa.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_tglSewa.setText("Tanggal Sewa");
        panel_TransSewa.add(lb_tglSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 413, -1, -1));

        date_tglSewa.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        panel_TransSewa.add(date_tglSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 413, 250, 26));

        lb_noTransSewa.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_noTransSewa.setText("No Transaksi Sewa");
        panel_TransSewa.add(lb_noTransSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        txt_noTransSewa.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_noTransSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noTransSewaActionPerformed(evt);
            }
        });
        txt_noTransSewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_noTransSewaKeyTyped(evt);
            }
        });
        panel_TransSewa.add(txt_noTransSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 457, 250, -1));

        lb_namaBrgSewa.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_namaBrgSewa.setText("Nama Barang Sewa");
        panel_TransSewa.add(lb_namaBrgSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 504, -1, -1));

        cb_namaBrgSewa.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cb_namaBrgSewa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Nama Barang--", "AC Portable 1 PK", "AC Portable 1,5 PK", "AC Split 1 PK", "AC Split 2 PK", "AC Standing 3 PK", "AC Standing 5 PK", "Misty Cool" }));
        panel_TransSewa.add(cb_namaBrgSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 501, 250, -1));

        lb_jmlBrgSewa.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_jmlBrgSewa.setText("Jumlah Barang Sewa");
        panel_TransSewa.add(lb_jmlBrgSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 548, -1, -1));

        txt_jmlBrgSewa.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_jmlBrgSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jmlBrgSewaActionPerformed(evt);
            }
        });
        txt_jmlBrgSewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_jmlBrgSewaKeyTyped(evt);
            }
        });
        panel_TransSewa.add(txt_jmlBrgSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 545, 250, -1));

        lb_hargaSatuan.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_hargaSatuan.setText("Harga Satuan");
        panel_TransSewa.add(lb_hargaSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 592, -1, -1));

        txt_hargaSatuan.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_hargaSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaSatuanActionPerformed(evt);
            }
        });
        txt_hargaSatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_hargaSatuanKeyTyped(evt);
            }
        });
        panel_TransSewa.add(txt_hargaSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 589, 250, -1));

        lb_totalHarga.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lb_totalHarga.setText("Total Harga");
        panel_TransSewa.add(lb_totalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 636, -1, -1));

        txt_totalHarga.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_totalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalHargaActionPerformed(evt);
            }
        });
        txt_totalHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_totalHargaKeyTyped(evt);
            }
        });
        panel_TransSewa.add(txt_totalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 633, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_TransSewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_TransSewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        //simpan("");
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        //edit("");
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        //hapus("");
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        //reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void txt_pencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pencarianKeyReleased
        //tampilData("");
    }//GEN-LAST:event_txt_pencarianKeyReleased

    private void tb_transPnwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_transPnwMouseClicked
        //klikTabel("");
    }//GEN-LAST:event_tb_transPnwMouseClicked

    private void txt_kodePlgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kodePlgKeyTyped
//        char c = evt.getKeyChar();
//        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
//            evt.consume();
//        }
    }//GEN-LAST:event_txt_kodePlgKeyTyped

    private void txt_noTransSewaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_noTransSewaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noTransSewaKeyTyped

    private void txt_noTransSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noTransSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noTransSewaActionPerformed

    private void txt_jmlBrgSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jmlBrgSewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jmlBrgSewaActionPerformed

    private void txt_jmlBrgSewaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jmlBrgSewaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jmlBrgSewaKeyTyped

    private void txt_hargaSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaSatuanActionPerformed

    private void txt_hargaSatuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hargaSatuanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaSatuanKeyTyped

    private void txt_totalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalHargaActionPerformed

    private void txt_totalHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalHargaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalHargaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cb_namaBrgSewa;
    private com.toedter.calendar.JDateChooser date_tglSewa;
    private javax.swing.JLabel lb_TransSewa;
    private javax.swing.JLabel lb_alamatPlg;
    private javax.swing.JLabel lb_formTransSewa;
    private javax.swing.JLabel lb_hargaSatuan;
    private javax.swing.JLabel lb_jmlBrgSewa;
    private javax.swing.JLabel lb_kodePlg;
    private javax.swing.JLabel lb_namaBrgSewa;
    private javax.swing.JLabel lb_namaPlg;
    private javax.swing.JLabel lb_noTlpPlg;
    private javax.swing.JLabel lb_noTransSewa;
    private javax.swing.JLabel lb_pencarian;
    private javax.swing.JLabel lb_tglSewa;
    private javax.swing.JLabel lb_totalHarga;
    private javax.swing.JPanel panel_TransSewa;
    private javax.swing.JScrollPane scroll_alamat;
    private javax.swing.JScrollPane scroll_table;
    private Custom.TableCustom tb_transPnw;
    private javax.swing.JTextArea txt_alamatPlg;
    private javax.swing.JTextField txt_hargaSatuan;
    private javax.swing.JTextField txt_jmlBrgSewa;
    private javax.swing.JTextField txt_kodePlg;
    private javax.swing.JTextField txt_namaPlg;
    private javax.swing.JTextField txt_noTlpPlg;
    private javax.swing.JTextField txt_noTransSewa;
    private javax.swing.JTextField txt_pencarian;
    private javax.swing.JTextField txt_totalHarga;
    // End of variables declaration//GEN-END:variables
}
